engines:
    nodesecurity:
        enabled: true
    fixme:
        enabled: true
    eslint:
        enabled: true
        checks:
            radix:
                enabled: false
    duplication:
        enabled: true
        config:
            languages:
                - javascript
