engines:
#    nodesecurity:
#        enabled: true
    fixme:
        enabled: true
    eslint:
        enabled: true
        checks:
            radix:
                enabled: false
            complexity:
                enabled: false
            global-require:
                enabled: false
    duplication:
        enabled: true
        config:
            languages:
                - javascript
ratings:
    paths:
        - "**.inc"
        - "**.js"
        - "**.jsx"
        - "**.module"
        - "**.php"
        - "**.py"
        - "**.rb"
exclude_paths:
    - "res/"
    - "private/"
